### ISSUE TITLE
revert partner order

### ISSUE THREAD

**Issue by gammam** [pagopa/site-pagopa.gov.it#115]
Change paragraph order in https://www.pagopa.gov.it/it/pubbliche-amministrazioni/partner-intermediari/ : 
- Partner Tecnologici qualificati
- Partner Tecnologici
- Intermediari Tecnologici

**Comment by vito80ba** [comment]
Closed by https://github.com/pagopa/site-pagopa.gov.it/commit/4eb8bc7b5047649aeb5e3ad9a15debc2c31a8ed0
