### ISSUE TITLE
add Captcha to mailinglist subscription form

### ISSUE THREAD

**Issue by gammam** [pagopa/site-pagopa.gov.it#2]
In order to protects mailinglist subscriptions against bots, add a captcha code to  [mailing-list subscription form](_includes/pages/home/home-newsletter-box.html).

**Comment by vito80ba** [comment]
Il sito web è fatto in Jekyll ed è staticizzato. 
I sistemi di captcha prevedono una parte server che validi il widget... e con un sito statico questa parte è inesistente.
Chiedere a fornitore sistema newsletter se prevede questa feature e implementarla su sito
