### ISSUE TITLE
Elenco dei PSP attivi

### ISSUE THREAD

**Issue by gammam** [pagopa/site-pagopa.gov.it#3]
La sezione it/prestatori-servizi-di-pagamento/elenco-PSP-attivi.md  deve mostrare l'elenco dei PSP attivi.
Ogni PSP è identificato da un logo ed un nome.

Azioni:  
- cliccando sul logo del PSP si viene re-direzionati verso la pagina del PSP
- deve essere possibile filtrare la lista ricercando il nome del PSP

Dati: 
- stiamo contattando i PSP a fornire i dati da mostrare, se definiamo delle specifiche ( esempio risoluzione e dimensione del logo ) possiamo dare le corrette indicazioni ai PSP per ottenere le informazioni necessari. 

Open items: 
- come possiamo gestire l'aggiornamento delle informazioni ?

**Comment by vito80ba** [comment]
### Ipotesi distribuita
Analogamente a quanto fatto per Developers Italia
https://developers.italia.it/it/riuso/pubblicazione/

Si può stilare un file "comune" per tutti i PSP. Tale file strutturato (es. psp.yml) può essere ospitato da ogni PSP nel proprio sito web istituzionale. 
Sul repo del sito di PagoPA ci sarà un elenco dei PSP che indica il solo url di psp.yml, esempio:
- title: Banco Popolare di XYZ
   pspurl: https://bancopopolarexyz.it/psp.yml
- title: Banca commerciale di Ripiti
   pspurl: https://bancacommercialeripiti.com/psp.yml

Il sito web di pagoPa ad ogni "rigenerazione" provvederà con apposito script a fare scraping dei dati e a impaginarli sulla pagina web strutturata.
Esempio similare di rendering informazioni:
https://developers.italia.it/it/cosa-fare/

### Ipotesi centralizzata
Aggiornamento di tutte le info in carico a PagoPA. Verrà predisposta apposito foglio di lavoro su Google Drive aziendale dove un incaricato provvederà a compilare ogni riga con PSP e ogni colonna con gli attributi che lo identificano (es. Nome, Logo, Indirizzo, ID, etc).
Il sito web di pagoPa ad ogni "rigenerazione" provvederà con apposito script a fare scraping dei dati e a impaginarli sulla pagina web strutturata.
Esempio similare di rendering informazioni:
https://developers.italia.it/it/cosa-fare/

**Comment by gammam** [comment]
Vista la difficoltà che sto avendo per avere i loghi, dubito che avremo a breve la disponibilità degli aderenti a fornire il puntamento dei file .yml per l'ipotesi distribuita.
Andrei quindi per l'ipotesi centralizzata.

**Comment by gammam** [comment]
eliminiamo le liste visto che al momento non abbiamo i loghi,altrimenti non riusciamo ad aggiornare il sito
