### ISSUE TITLE
Nuova Sezione  - Come Aderire -

### ISSUE THREAD

**Issue by gammam** [pagopa/site-pagopa.gov.it#4]
All'interno della sezione Prestatori Servizi di Pagamento è necessario aggiungere una nuova sotto sezione denominata "Come Aderire"

Testo della pagina 

> Per avviare la procedura di adesione a pagoPA:
> 
> Scegli il modello di accordo che meglio risponde alle tue necessità: 
> 
> - Modello A [download del file pdf al click]: se vuoi un modello di tariffazione che premia i grandi volumi. Con questo tipo di accordo è possibile cumulare i propri volumi alternativamente con altri PSP appartenenti al medesimo gruppo societario o tramite un Mandatario Qualificato.
> 
> - Modello B [download del file al click]: se vuoi un modello di tariffazione che prevede una flat fee su alcune casistiche.
> 
> Scarica il modulo relativo al modello di accordo prescelto, firmalo digitalmente e invialo a: accordipsp@pec.pagopa.it [mailto:]
> 
> In seguito...
> Per qualsiasi chiarimento sulla procedura di adesione, puoi consultare le nostre FAQ o scrivere all’indirizzo helpdesk@pagopa.it [mailto:]

**Comment by vito80ba** [comment]
@gammam esiste già la pagina. E' solo da rinnovare?
https://www.pagopa.gov.it/it/prestatori-servizi-di-pagamento/come-aderire/

**Comment by gammam** [comment]
Si
