### ISSUE TITLE
Nuova Sottosezione Intermediari e Mandatari

### ISSUE THREAD

**Issue by gammam** [pagopa/site-pagopa.gov.it#5]
All'interno della sezione Prestatori Servizi pagamenti, inserire la Sottosezione denominata **Intermediari e Mandatari**
 Contenuto della pagina

> # Intermediario tecnologico
> Cos’è un intermediario tecnologico?
> Il soggetto che, in qualità di operatore per l'intermediazione tecnologica, offre - previa adesione alla piattaforma pagoPA - ai PSP Aderenti un servizio tecnologico per il collegamento e per lo scambio dei flussi con la piattaforma pagoPA, nel pieno rispetto delle Linee Guida e dei relativi standard tecnici.
> 
> ## Cosa fare per diventare intermediario?
> 
> Se sei già un PSP, non devi fare nulla. L’accordo che hai firmato come PSP copre anche il tuo ruolo come intermediario. 
> Se sei già un Mandatario Qualificato, non devi fare nulla. L’accordo che hai firmato come Mandatario prevede che tu possa operare anche nel ruolo di Intermediario copre anche il tuo ruolo come Intermediario. 
> Se non sei né un PSP né un mandatario Qualificato e desideri svolgere il ruolo di Intermediario Tecnologico, scrivici a legal@pagopa.it per richiedere  l’accordo da stipulare con la PagoPA S.p.A. 
> 
> ## Come un PSP può usufruire di un Intermediario ?
> Scrivere ad accordipsp@pec.pagopa.it allegando il catalogo dati informativi aggiornato con le informazioni fornite dall’Intermediario.  
> # Mandatario Qualificato
> 
> Cos’è un Mandatario?
> La persona giuridica che svolge il ruolo di Intermediario Tecnologico e che, previa stipula di apposito accordo con PagoPA S.p.A. e previo mandato* ricevuto dal Prestatore Aderente, si è impegnata ed è legittimata a pagare i Corrispettivi per conto dei Prestatori Aderenti che le hanno dato Mandato.
> 
> Il Mandatario Qualificato è un soggetto che si è accreditato come tale con la pagoPA s.p.a.. 
> ## Lista mandatari 
>  Elenco con campo di ricerca per Nome e Logo 
> 
> 
> ## Cosa fare per diventare Mandatario?
> Scrivici a legal@pagopa.it per ottenere l’accordo da stipulare con la PagoPA S.p.A
> 
> ## Come un PSP può  indicare un Mandatario ?
> Scrivere ad accordipsp@pec.pagopa.it indicando, per ogni servizio di pagamento che si intende offrire su pagoPA, il Mandatario di cui si vuole usufruire.
>

**Comment by vito80ba** [comment]
Lista mandatari: cosa/come inserire?

**Comment by gammam** [comment]
sempre logo e nome. Questa sicuramente centralizzata come informazione.

**Comment by vito80ba** [comment]
Sottoposta grafica su branch 5-psp-itnermediari con lista centralizzata su apposito file YML.
Attendo feedback e contenuti "reali"

**Comment by gammam** [comment]
eliminiamo le liste per il momento visto che non abbiamo i loghi
